# Generated by Django 4.0.6 on 2022-07-12 08:30

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default=('49.42068036706076, 26.98829291813987'), max_length=100),
            preserve_default=False,
        ),
    ]
