# Generated by Django 4.0.6 on 2022-07-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options'),
        ('cart', '0011_customer_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=45, help_text='the total price of the products in cart item', max_digits=12, verbose_name='sub_total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='active',
            field=models.BooleanField(default=True, help_text='indicator of the state of the cart item', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='communication with the Cart model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, help_text='communication with the Order model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(help_text='communication with the Product model', on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(help_text='the quantity of the product in the cart item', verbose_name='quantity'),
        ),
    ]
