# Generated by Django 4.0.6 on 2022-07-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_customer_address_alter_customer_geolocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, help_text='the total price of the products in cart item', max_digits=12, verbose_name='total price'),
        ),
    ]
