# Generated by Django 4.0.6 on 2022-07-07 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shared.mixins.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='shop name', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='used to generate URL', unique=True)),
                ('image', models.ImageField(blank=True, help_text='shop logo', null=True, upload_to='logo/%Y/%m/%d', verbose_name='logo')),
                ('img_alt', models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=150, null=True, verbose_name='image alternative')),
                ('phone', models.CharField(help_text='The phone number must be in the format: "+380999999999"', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='The phone number must be in the format: "+380999999999". Starts with "+380" and 9 digits.', regex='^\\+380\\d{9}')], verbose_name='phone number')),
                ('email', models.EmailField(help_text='shop email', max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['-created'],
            },
            bases=(models.Model, shared.mixins.model_utils.ImageNameMixins),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='product name', max_length=250, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='used to generate URL', unique=True)),
                ('description', models.TextField(blank=True, help_text='product description', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='the price of the product', max_digits=10, verbose_name='price')),
                ('image', models.ImageField(blank=True, help_text='product image', null=True, upload_to='product/%Y/%m/%d', verbose_name='image')),
                ('img_alt', models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=150, null=True, verbose_name='image alternative')),
                ('stock', models.IntegerField(help_text='product quantity in stock', verbose_name='stock')),
                ('available', models.BooleanField(default=True, help_text='available product or not', verbose_name='available')),
                ('shop', models.ForeignKey(help_text='shop to which the product belongs', on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created'],
            },
            bases=(models.Model, shared.mixins.model_utils.ImageNameMixins),
        ),
    ]
