# Generated by Django 4.0.6 on 2022-07-19 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['shop', '-created'], 'verbose_name': 'product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, help_text='product description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(blank=True, help_text='product description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_alt_en',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=150, null=True, verbose_name='image alternative'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_alt_uk',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=150, null=True, verbose_name='image alternative'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(help_text='product name', max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(help_text='product name', max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='shop',
            name='img_alt_en',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=150, null=True, verbose_name='image alternative'),
        ),
        migrations.AddField(
            model_name='shop',
            name='img_alt_uk',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=150, null=True, verbose_name='image alternative'),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_en',
            field=models.CharField(help_text='shop name', max_length=200, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_uk',
            field=models.CharField(help_text='shop name', max_length=200, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
    ]
