# Generated by Django 4.0.6 on 2022-07-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['shop'], 'verbose_name': 'product', 'verbose_name_plural': 'Products'},
        ),
    ]
